# Generated by Django 5.1 on 2024-08-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-name'], 'verbose_name': 'Product'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=100, upload_to='photos/%y/%m/%d', width_field=100),
        ),
    ]
